server:
  port: 9014
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: stock
  datasource:
    url: jdbc:mysql://localhost:3306/demo2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ahmet
    hikari:
      connection-timeout: 3000000
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  cloud:
    discovery:
      enabled: true
